version: "3"
services:

  app:
    ports:
      - "6379"
    build: .
    environment:
        PORT: 8888
        DATABASE_URL: postgres://heike:assword@db:5432/heike?sslmode=disable
        SECRET: secret
        KEY: key
        NODE: node
        DAI: dai
        SYMBOL: symbol
        RETAINER: retainer
    links:
      - db
    depends_on:
      - db



  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: heike
      POSTGRES_PASSWORD: assword
      # : CREATE EXTENSION IF NOT EXISTS "uuid-ossp"   will do it later


